---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "jiralerts.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "jiralerts.fullname" . }}
data:
  jira-username: {{ .Values.jira.username | b64enc | quote }}
  jira-password: {{ .Values.jira.password | b64enc | quote }}
